
#ifndef BLOCKCHAINSTATUS_H_
#define BLOCKCHAINSTATUS_H_

typedef enum{
		STATUS_OK,
		STATUS_READING_COMMANDS,
		STATUS_NO_MORE_COMMANDS,
		STATUS_NO_BLOCKS_TO_CONVERT,
		STATUS_NO_ORIGIN_BLOCK_MINED,
		STATUS_ERROR_HASH_NOT_FOUND,
		STATUS_ERROR_COMMAND_PAYLOAD,
		STATUS_ERROR_COMMAND_NOT_FOUND,
		STATUS_CORRUPT_FORMAT,
		STATUS_CORRUPT_FORMAT_BAD_BITS,
		STATUS_CORRUPT_FORMAT_BAD_NONCE,
		STATUS_CORRUPT_FORMAT_BAD_HASH,
		STATUS_CORRUPT_FORMAT_BAD_TXINDEX,
		STATUS_CORRUPT_FORMAT_BAD_TXIN,
		STATUS_CORRUPT_FORMAT_BAD_TXOUT,
		STATUS_CORRUPT_FORMAT_BAD_BTCVALUE,
		STATUS_BAD_ALLOC,
		STATUS_BAD_READ_INPUT_FILE,
		STATUS_BAD_READ_OUTPUT_FILE,
		STATUS_FINISH_CONVERT_SUCCESSFULY,
		STATUS_OPEN_FILE_SUCCESSFULY,
		STATUS_CLOSE_FILE_SUCCESSFULY,
		STATUS_ERROR_LIST_OF_TRANSACT_NOT_SUPPORTED,
		STATUS_USER_WITHOUT_BTC,
}status_t;




#endif /* BLOCKCHAINSTATUS_H_ */
